# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms\UI\aims_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dollar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 811, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/money_background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -8, 821, 761))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setStyleSheet("color: rgb(255,255,255);\n"
"background: rgb(120, 183, 140);\n"
"font: 20px;\n"
"padding: 5px;\n"
"border-radius: 10px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.aimNameEdit = QtWidgets.QLineEdit(self.frame_5)
        self.aimNameEdit.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(120, 183, 140);;\n"
"    border-radius: 10px;\n"
"    font: 17px;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 2px solid rgb(120, 155, 140);\n"
"}")
        self.aimNameEdit.setObjectName("aimNameEdit")
        self.verticalLayout_3.addWidget(self.aimNameEdit)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("color: rgb(255,255,255);\n"
"background: rgb(120, 183, 140);\n"
"font: 20px;\n"
"padding: 5px;\n"
"border-radius: 10px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.aimSumEdit = QtWidgets.QLineEdit(self.frame_6)
        self.aimSumEdit.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(120, 183, 140);;\n"
"    border-radius: 10px;\n"
"    font: 17px;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 2px solid rgb(120, 155, 140);\n"
"}")
        self.aimSumEdit.setObjectName("aimSumEdit")
        self.verticalLayout_4.addWidget(self.aimSumEdit)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setStyleSheet("color: rgb(255,255,255);\n"
"background: rgb(120, 183, 140);\n"
"font: 20px;\n"
"padding: 5px;\n"
"border-radius: 10px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.aimDateEdit = QtWidgets.QDateEdit(self.frame_7)
        self.aimDateEdit.setStyleSheet("QDateEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(120, 183, 140);;\n"
"    border-radius: 10px;\n"
"    font: 17px;\n"
"}\n"
"\n"
"QDateEdit::hover {\n"
"    border: 2px solid rgb(120, 155, 140);\n"
"}")
        self.aimDateEdit.setObjectName("aimDateEdit")
        self.verticalLayout_6.addWidget(self.aimDateEdit)
        self.frame_2 = QtWidgets.QFrame(self.frame_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aimList = QtWidgets.QListWidget(self.frame_2)
        self.aimList.setObjectName("aimList")
        self.horizontalLayout.addWidget(self.aimList)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.deleteAimBtn = QtWidgets.QPushButton(self.frame_4)
        self.deleteAimBtn.setStyleSheet("QPushButton#deleteAimBtn {\n"
"     color: rgb(255, 255, 255);\n"
"    background-color: rgb(195, 0, 0);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#deleteAimBtn:hover {\n"
"    background-color: rgb(170, 0, 0);\n"
" }")
        self.deleteAimBtn.setObjectName("deleteAimBtn")
        self.verticalLayout_2.addWidget(self.deleteAimBtn)
        self.redactAimBtn = QtWidgets.QPushButton(self.frame_4)
        self.redactAimBtn.setStyleSheet("QPushButton#redactAimBtn {\n"
"     color: rgb(255, 255, 255);\n"
"background-color: rgb(245, 158, 47);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#redactAimBtn:hover {\n"
"background-color: rgb(245, 129, 33);\n"
" }")
        self.redactAimBtn.setObjectName("redactAimBtn")
        self.verticalLayout_2.addWidget(self.redactAimBtn)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.infoLbl = QtWidgets.QLabel(self.frame_3)
        self.infoLbl.setEnabled(True)
        self.infoLbl.setStyleSheet("color: white;\n"
"background-color: rgb(44, 153, 255);\n"
"font: 15px;\n"
"padding: 5px;\n"
"border-radius: 10px;\n"
"font-weight: bold;")
        self.infoLbl.setObjectName("infoLbl")
        self.horizontalLayout_2.addWidget(self.infoLbl)
        self.backMenuBtn = QtWidgets.QPushButton(self.frame_3)
        self.backMenuBtn.setStyleSheet("QPushButton#backMenuBtn {\n"
"     color: rgb(255, 255, 255);\n"
"    background-color: rgb(120, 183, 140);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#backMenuBtn:hover {\n"
"     background-color: rgb(120, 170, 140);\n"
" }")
        self.backMenuBtn.setObjectName("backMenuBtn")
        self.horizontalLayout_2.addWidget(self.backMenuBtn)
        self.clearFormBtn = QtWidgets.QPushButton(self.frame_3)
        self.clearFormBtn.setStyleSheet("QPushButton#clearFormBtn {\n"
"     color: rgb(255, 255, 255);\n"
"    background-color: rgb(120, 183, 140);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#clearFormBtn:hover {\n"
"     background-color: rgb(120, 170, 140);\n"
" }")
        self.clearFormBtn.setObjectName("clearFormBtn")
        self.horizontalLayout_2.addWidget(self.clearFormBtn)
        self.addAimBtn = QtWidgets.QPushButton(self.frame_3)
        self.addAimBtn.setStyleSheet("QPushButton#addAimBtn {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(120, 183, 140);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#addAimBtn:hover {\n"
"     background-color: rgb(120, 170, 140);\n"
" }")
        self.addAimBtn.setObjectName("addAimBtn")
        self.horizontalLayout_2.addWidget(self.addAimBtn)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyMoneyManager"))
        self.label_4.setText(_translate("MainWindow", "Название цели"))
        self.label_5.setText(_translate("MainWindow", "Сумма для приобретения"))
        self.label_7.setText(_translate("MainWindow", "Желаемая дата достижения цели"))
        self.deleteAimBtn.setText(_translate("MainWindow", "Удалить"))
        self.redactAimBtn.setText(_translate("MainWindow", "Редактировать"))
        self.infoLbl.setText(_translate("MainWindow", "Запись успешно добавлена!"))
        self.backMenuBtn.setText(_translate("MainWindow", "Назад"))
        self.clearFormBtn.setText(_translate("MainWindow", "Очистить"))
        self.addAimBtn.setText(_translate("MainWindow", "Добавить"))
from Pictures.Images import design


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
