# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms\UI\recomendation_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dollar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-16, -5, 821, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/money_background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-2, 0, 801, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setStyleSheet("color: rgb(255,255,255);\n"
"background: rgb(120, 183, 140);\n"
"font: 20px;\n"
"padding: 5px;\n"
"border-radius: 10px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.choseAimComboBox = QtWidgets.QComboBox(self.frame_8)
        self.choseAimComboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(120, 183, 140);;\n"
"    border-radius: 10px;\n"
"    font: 17px;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border: 2px solid rgb(120, 155, 140);\n"
"}")
        self.choseAimComboBox.setObjectName("choseAimComboBox")
        self.verticalLayout_6.addWidget(self.choseAimComboBox)
        self.verticalLayout.addWidget(self.frame_8)
        self.recomendationPlainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.recomendationPlainTextEdit.setObjectName("recomendationPlainTextEdit")
        self.verticalLayout.addWidget(self.recomendationPlainTextEdit)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryToDecreaseLbl = QtWidgets.QLabel(self.frame_2)
        self.categoryToDecreaseLbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid #094065;\n"
"border-radius: 19px; \n"
"background-color: rgb(0, 179, 255);\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"")
        self.categoryToDecreaseLbl.setText("")
        self.categoryToDecreaseLbl.setObjectName("categoryToDecreaseLbl")
        self.horizontalLayout.addWidget(self.categoryToDecreaseLbl)
        self.backMenuBtn = QtWidgets.QPushButton(self.frame_2)
        self.backMenuBtn.setStyleSheet("QPushButton#backMenuBtn {\n"
"     color: rgb(255, 255, 255);\n"
"    background-color: rgb(120, 183, 140);\n"
"    border: 1px solid #094065;\n"
"    border-radius: 19px; \n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
" }\n"
" QPushButton#backMenuBtn:hover {\n"
"     background-color: rgb(120, 170, 140);\n"
" }")
        self.backMenuBtn.setObjectName("backMenuBtn")
        self.horizontalLayout.addWidget(self.backMenuBtn)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyMoneyManager"))
        self.label_7.setText(_translate("MainWindow", "Выберете цель"))
        self.backMenuBtn.setText(_translate("MainWindow", "Назад"))
from Pictures.Images import design


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
